export class SearchObjectStaff {
  pageIndex = 1;
  pageSize = 10;
  keyword = null;
  employeeStatus = null;
  employeeStatusId = null;
  civilServantTypeId = null;
  academicTitleLevel = null;
  educationDegreeLevel = null;
  contractOrganization = null;
  contractOrganizationId = null;
  workOrganization = null;
  workOrganizationId = null;
  organization = null;
  organizationId = null;
  department = null;
  departmentId = null;
  departments = [];
  departmentIds = [];
  positionTitle = null;
  positionTitleId = null;
  administrativeunit = null;
  gender = null;
  fromStartDate = null;
  toStartDate = null;
  workplace = null;
  workplaceId = null;
  staffPhase = null; // Tình trạng nhân viên
  contractNumber = null;
  provinceId = null; // Tỉnh thường trú
  province = null;
  districtId = null; // Huyện thường trú
  district = null;
  communeId = null; // Xã thường trú
  commune = null;
  currentResidence = null; //tạm trú (nơi ở hiện tại)
  birthPlace = null; // Quê quán
  idNumber = null; // CMND/CCCD
  maritalStatus = null; // Tình trạng hôn nhân
  taxCode = null; // Mã số thuế
  healthInsuranceNumber = null; // Mã số bảo hiểm y tế (BHYT)
  socialInsuranceNumber = null; // Mã số BHXH
  socialInsuranceNote = null; // Tình trạng sổ BHXH
  introducerId = null; // Nhân viên giới thiệu nhân viên này vào làm
  introducer = null;
  recruiterId = null; // Nhân viên quyết định tuyển dụng nhân viên này vào làm
  recruiter = null;
  staffDocumentStatus = null; // Tình trạng hoàn thành hồ sơ của nhân viên. Chi tiết: HrConstants.StaffDocumentStatus
  rankTitleId = null; // Cấp bậc
  rankTitle = null;
  directManager = null; // Vị trí quản lý trực tiếp
  hasSocialInsuranceNumber = null; // Có tham gia BHXH
  tab = null;
  position = null;
  positionId = null;
  fromBirthDate = null;
  toBirthDate = null;
  birthMonths = [];
  year = new Date().getFullYear();
  staffWorkShiftType = null; // Loại làm việc. HrConstants.StaffWorkShiftType
  fixShiftWorkId = null; // Ca làm việc cố định nếu loại làm việc của nhân viên là cố định. HrConstants.StaffWorkShiftType.FIX
  fixShiftWork = null;
  staffLeaveShiftType = null; // Loại nghỉ làm việc. HrConstants.StaffLeaveShiftType
  fixLeaveWeekDay = null; // Ngày nghỉ cố định trong tuần, có giá trị khi loại nghỉ cửa nhân viên là nghỉ cố định. HrConstants.WeekDays
  //Thời gian tuyển dụng
  fromRecruitmentDate = null;
  toRecruitmentDate = null;
  //thời gian nghỉ thai sản
  fromMaternityLeave = null;
  toMaternityLeave = null;
  maternityLeaveEnded = false;
  endSocialInsFromDate = null; // kết thúc đóng BHXH từ ngày
  endSocialInsToDate = null; // kết thúc đóng BHXH đến ngày
}
